#!/bin/bash
set -euo pipefail

# ===========================================
# Sync Environment Files to Repos
# ===========================================
# Generates repo-specific .env files from the orchestration master config.
# Each repo expects different variable names - this script translates.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORCH_DIR="$(dirname "$SCRIPT_DIR")"

# Load shared libraries
source "$SCRIPT_DIR/lib/logging.sh"
source "$SCRIPT_DIR/lib/env.sh"
source "$SCRIPT_DIR/lib/prereqs.sh"
if ! load_env "$ORCH_DIR/.env"; then
    echo "Error: $ORCH_DIR/.env not found"
    echo "Run: cp .env.example .env"
    exit 1
fi

require_tool python3
require_tool pnpm

echo "==========================================="
echo "  Sync Environment Files"
echo "==========================================="
echo ""

# ===========================================
# Resolve public-facing URLs from PUBLIC_HOST
# ===========================================
# PUBLIC_HOST and PUBLIC_PROTOCOL come from the master .env (set by keygen).
# When PUBLIC_HOST is non-loopback (testnet/staging), auto-derive the browser-
# facing URLs so the user only needs to set PUBLIC_HOST + PUBLIC_PROTOCOL.
_PUB_HOST="${PUBLIC_HOST:-127.0.0.1}"
_PUB_PROTO="${PUBLIC_PROTOCOL:-http}"

_is_loopback() {
    case "$1" in
        localhost|0.0.0.0|127.*) return 0 ;;
        *) return 1 ;;
    esac
}

if _is_loopback "$_PUB_HOST"; then
    # Local dev — direct to localhost ports
    _ANVIL_RPC="${NEXT_PUBLIC_ANVIL_RPC:-}"
    _API_URL="${NEXT_PUBLIC_API_URL:-http://${_PUB_HOST}:7051}"
    _ANVIL_EXPLORER="${NEXT_PUBLIC_ANVIL_EXPLORER_URL:-http://${_PUB_HOST}:${BLOCKSCOUT_PORT:-4000}}"
else
    # Remote (testnet/staging) — route through reverse proxy
    _ANVIL_RPC="${NEXT_PUBLIC_ANVIL_RPC:-${_PUB_PROTO}://${_PUB_HOST}/rpc/evm}"
    _API_URL="${NEXT_PUBLIC_API_URL:-${_PUB_PROTO}://${_PUB_HOST}/api}"
    _ANVIL_EXPLORER="${NEXT_PUBLIC_ANVIL_EXPLORER_URL:-}"
fi

# ===========================================
# Generate zephyr-bridge .env.local
# ===========================================
log_info "Generating zephyr-bridge/.env.local..."

cat > "$BRIDGE_REPO_PATH/.env.local" << EOF
# Generated by bridge-orchestration/scripts/sync-env.sh
# Do not edit directly - modify orchestration .env instead

# === Environment ===
BRIDGE_ENV=${BRIDGE_ENV}
NEXT_PUBLIC_BRIDGE_ENV=${BRIDGE_ENV}

# === EVM (Local) ===
EVM_RPC_HTTP_LOCAL=${EVM_RPC_HTTP}
EVM_RPC_WS_LOCAL=${EVM_RPC_WS}
EVM_CHAIN_ID_LOCAL=${EVM_CHAIN_ID}

# === EVM (Sepolia) ===
EVM_RPC_HTTP_SEPOLIA=${EVM_RPC_HTTP_SEPOLIA:-}
EVM_RPC_WS_SEPOLIA=${EVM_RPC_WS_SEPOLIA:-}
EVM_CHAIN_ID_SEPOLIA=11155111

# === Bridge Signer ===
BRIDGE_PK=${BRIDGE_PK#0x}

# === Zephyr Wallet RPC ===
ZEPH_WALLET_RPC_SERVER=${ZEPH_WALLET_RPC_SERVER}
ZEPH_WALLET_RPC_PORT=${ZEPH_WALLET_RPC_PORT}
ZEPH_RPC_TIMEOUT_MS=${ZEPH_RPC_TIMEOUT_MS}

# === Redis ===
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_DB=${REDIS_DB}

# === Database ===
DATABASE_URL=${DATABASE_URL_BRIDGE}

# === UI Settings ===
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:-}
NEXT_PUBLIC_REOWN_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:-placeholder}
NEXT_PUBLIC_ENABLE_DEV_CONTROLS=${NEXT_PUBLIC_ENABLE_DEV_CONTROLS}
NEXT_PUBLIC_ZEPHYR_EXPLORER_BASE=https://explorer.zephyrprotocol.com/tx/

# === Public Host (browser-facing URLs) ===
NEXT_PUBLIC_ANVIL_LOCAL_HOST=${_PUB_HOST}
NEXT_PUBLIC_ANVIL_RPC=${_ANVIL_RPC}
NEXT_PUBLIC_API_URL=${_API_URL}
NEXT_PUBLIC_ZEPHYR_DAEMON_RPC=${_PUB_HOST}:47767
NEXT_PUBLIC_ANVIL_EXPLORER_URL=${_ANVIL_EXPLORER}

# === Token Config ===
NEXT_PUBLIC_USE_WZSD=1
NEXT_PUBLIC_USE_WZEPH=1
NEXT_PUBLIC_USE_WZYS=1
NEXT_PUBLIC_USE_WZRS=1

# === Confirmations ===
NEXT_PUBLIC_EVM_CONFIRMATIONS=5
NEXT_PUBLIC_ZEPH_CONFIRMATIONS=5

# === Beta Access Gate ===
NEXT_PUBLIC_BETA_TOKEN=${NEXT_PUBLIC_BETA_TOKEN:-}

# === Background Workers (disabled - use Procfile) ===
BOOTSTRAP_ZEPHYR_LISTENER=0
BOOTSTRAP_CLAIM_WATCHER=0
BOOTSTRAP_UNWRAP_WATCHER=0
BOOTSTRAP_UNISWAP_V4_POSITIONS=0
BOOTSTRAP_UNISWAP_V4_ACTIVITY=0

# === Admin ===
ADMIN_TOKEN=${ADMIN_TOKEN}
EOF

log_success "Created $BRIDGE_REPO_PATH/.env.local"

# Sync addresses to bridge
log_info "Syncing addresses to bridge..."
ADDR_SRC="${ORCHESTRATION_PATH}/config/addresses.local.json"
if [ -f "$ADDR_SRC" ]; then
  mkdir -p "$BRIDGE_REPO_PATH/apps/api/config"
  mkdir -p "$BRIDGE_REPO_PATH/packages/config/src/addresses"
  cp "$ADDR_SRC" "$BRIDGE_REPO_PATH/apps/api/config/addresses.local.json"
  cp "$ADDR_SRC" "$BRIDGE_REPO_PATH/packages/config/src/addresses/addresses.local.json"
  log_success "Copied addresses to bridge API + config package"
fi

# Build all internal packages (types → config → evm → bridge etc.)
# Required after address changes AND on fresh clones where dist/ doesn't exist yet.
log_info "Building bridge internal packages..."
(cd "$BRIDGE_REPO_PATH" && pnpm --filter './packages/*' build 2>/dev/null)
log_success "Bridge packages built"

# ===========================================
# Generate zephyr-bridge-engine .env
# ===========================================
log_info "Generating zephyr-bridge-engine/.env..."

# Remove .env.local if it exists — it overrides .env and causes stale config
if [ -f "$ENGINE_REPO_PATH/.env.local" ]; then
  rm "$ENGINE_REPO_PATH/.env.local"
  log_info "Removed stale $ENGINE_REPO_PATH/.env.local"
fi

cat > "$ENGINE_REPO_PATH/.env" << EOF
# Generated by bridge-orchestration/scripts/sync-env.sh
# Do not edit directly - modify orchestration .env instead

# === Environment ===
NODE_ENV=development
ZEPHYR_ENV=${BRIDGE_ENV}

# === EVM RPC (by environment) ===
RPC_URL_LOCAL_HTTP=${EVM_RPC_HTTP}
RPC_URL_LOCAL_WS=${EVM_RPC_WS}
RPC_URL_SEPOLIA_HTTP=${EVM_RPC_HTTP_SEPOLIA:-}
RPC_URL_SEPOLIA_WS=${EVM_RPC_WS_SEPOLIA:-}
RPC_URL_MAINNET_HTTP=

# === Zephyr Daemon ===
ZEPHYR_D_RPC_URL=${ZEPHYR_D_RPC_URL}
ZEPHYR_PAPER=false

# === EVM Wallet ===
EVM_WALLET_ADDRESS=${ENGINE_ADDRESS}
EVM_PRIVATE_KEY=${ENGINE_PK#0x}

# === Zephyr Wallet ===
ZEPHYR_WALLET_RPC_URL=http://127.0.0.1:48771/json_rpc
ZEPHYR_BRIDGE_ADDRESS=$(curl -sf http://localhost:48770/json_rpc \
  -d '{"jsonrpc":"2.0","id":"0","method":"get_address","params":{"account_index":0}}' 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('result',{}).get('address',''))" 2>/dev/null || echo "")

# === Database ===
DATABASE_URL=${DATABASE_URL_ENGINE}

# === MEXC ===
MEXC_PAPER=${MEXC_PAPER:-true}
MEXC_API_KEY=${MEXC_API_KEY:-}
MEXC_API_SECRET=${MEXC_API_SECRET:-}

# === CEX Wallets (fake exchange — real wallets for arb deposits/withdrawals) ===
CEX_ADDRESS=${CEX_ADDRESS}
CEX_PK=${CEX_PK#0x}
CEX_WALLET_RPC_URL=http://127.0.0.1:48772/json_rpc

# === App ===
NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}

# === Pool Watcher Defaults ===
UNISWAP_V4_START_BLOCK_LOCAL=0
UNISWAP_V4_START_BLOCK_SEPOLIA=9265810

# === Worker Ports ===
EVM_WATCHER_PORT=7010
MEXC_WATCHER_PORT=7020

# === Deployer (for seed scripts) ===
DEPLOYER_PRIVATE_KEY=${DEPLOYER_PRIVATE_KEY#0x}
DEPLOYER_ADDRESS=${DEPLOYER_ADDRESS}
FOUNDRY_REPO_PATH=${FOUNDRY_REPO_PATH}

# === Bridge API (for seed scripts) ===
BRIDGE_API_URL=http://127.0.0.1:7051

# === Admin ===
ADMIN_TOKEN=${ADMIN_TOKEN}
EOF

log_success "Created $ENGINE_REPO_PATH/.env"

# Sync addresses to engine repo
log_info "Syncing addresses to engine..."
if [ -f "${ORCHESTRATION_PATH}/config/addresses.local.json" ]; then
python3 -c "
import json, sys
src = json.load(open('${ORCHESTRATION_PATH}/config/addresses.local.json'))
# Token metadata (engine needs symbol + name)
META = {
  'USDC': ('USDC', 'USD Coin'),
  'USDT': ('USDT', 'Tether USD'),
  'wZEPH': ('WZEPH', 'Wrapped Zephyr'),
  'wZSD': ('WZSD', 'Wrapped Zephyr Stable Dollar'),
  'wZRS': ('WZRS', 'Wrapped Zephyr Reserve Stable'),
  'wZYS': ('WZYS', 'Wrapped Zephyr Yield Stable'),
}
tokens = {}
for k, t in src.get('tokens', {}).items():
    sym, name = META.get(k, (k, k))
    tokens[k] = {'address': t['address'], 'decimals': t['decimals'], 'symbol': sym, 'name': name}
out = {'version': src.get('version',1), 'chainId': src.get('chainId',31337), 'contracts': src['contracts'], 'tokens': tokens}
# Pass through seeding config (dynamic amounts from patch-pool-prices.py)
if 'seeding' in src:
    out['seeding'] = src['seeding']
# Convert pools object to array (engine expects PoolConfig[])
pools_obj = src.get('pools', {})
if pools_obj:
    pools = []
    for name, pool_data in pools_obj.items():
        entry = {'id': name}
        if 'plan' in pool_data:
            entry['plan'] = pool_data['plan']
        if 'state' in pool_data and 'poolId' in pool_data['state']:
            entry['address'] = pool_data['state']['poolId']
        pools.append(entry)
    out['pools'] = pools
json.dump(out, open('${ENGINE_REPO_PATH}/src/services/evm/config/addresses.local.json', 'w'), indent=2)
print('  Engine addresses synced (with ' + str(len(pools_obj)) + ' pools)')
"
else
  log_info "No addresses.local.json yet — skipping engine address sync (run make dev-setup first)"
fi

# ===========================================
# Summary
# ===========================================
echo ""
echo "==========================================="
log_success "Environment files synced"
echo "==========================================="
echo ""
echo "Generated:"
echo "  - $BRIDGE_REPO_PATH/.env.local"
echo "  - $BRIDGE_REPO_PATH/apps/api/config/addresses.local.json"
echo "  - $BRIDGE_REPO_PATH/packages/config/src/addresses/addresses.local.json"
echo "  - $ENGINE_REPO_PATH/.env"
echo "  - $ENGINE_REPO_PATH/src/services/evm/config/addresses.local.json"
echo ""
echo "To update, edit $ORCH_DIR/.env then run this script again."
echo ""
